- name: AAP2 Demo | Add SCM Credentials for Projects
  when: aap2_scm_credentials is defined and aap2_scm_credentials | length > 0
  ansible.controller.credential:
    controller_host: "{{ aap2_controller_host }}"
    controller_username: "{{ aap2_controller_username }}"
    controller_password: "{{ aap2_controller_password }}"
    organization: "{{ aap2_organization | default('Default', true) }}"
    validate_certs: "{{ aap2_controller_validate_ssl | default(false, true) }}"
    name: "{{ item.name }}"
    state: present
    credential_type: "Source Control"
    inputs:
      username: "{{ item.scm_username | default(omit, true) }}"
      password: "{{ item.scm_password | default(omit, true) }}"
      ssh_key_data: "{{ item.scm_ssh_key | default(omit, true) }}"
  loop: "{{ aap2_scm_credentials }}"
  no_log: true

- name: AAP2 Demo | Add Machine credential for Templates
  when: aap2_machine_credentials is defined and aap2_machine_credentials | length > 0
  ansible.controller.credential:
    controller_host: "{{ aap2_controller_host }}"
    controller_username: "{{ aap2_controller_username }}"
    controller_password: "{{ aap2_controller_password }}"
    organization: "{{ aap2_organization | default('Default', true) }}"
    validate_certs: "{{ aap2_controller_validate_ssl | default(false, true) }}"
    name: "{{ item.name }}"
    state: present
    credential_type: 'Machine'
    inputs:
      username: "{{ item.username | default('sysadmin', true) }}"
      password: "{{ item.password | default('redhat', true) }}"
      # ssh_key_data: "{{ item.ssh_key | default(lookup('file', '~/.ssh/id_rsa')) }}"
  loop: "{{ aap2_machine_credentials }}"
  no_log: true

- name: AAP2 Demo | Add Cloud credentials for Templates/Inventory
  when: aap2_cloud_credentials is defined and aap2_cloud_credentials | length > 0
  ansible.controller.credential:
    controller_host: "{{ aap2_controller_host }}"
    controller_username: "{{ aap2_controller_username }}"
    controller_password: "{{ aap2_controller_password }}"
    organization: "{{ aap2_organization | default('Default', true) }}"
    validate_certs: "{{ aap2_controller_validate_ssl | default(false, true) }}"
    name: "{{ item.name }}"
    state: present
    credential_type: "{{ item.credential_type }}"
    inputs:
      tenant: "{{ item.azure_tenant | default(omit, true) }}"
      subscription: "{{ item.azure_subscription | default(omit, true) }}"
      client: "{{ item.azure_client | default(omit, true) }}"
      secret: "{{ item.azure_secret | default(omit, true) }}"
      username: "{{ item.aws_access_key | default(omit, true) }}"
      password: "{{ item.aws_secret_key | default(omit, true) }}"
  loop: "{{ aap2_cloud_credentials }}"
  no_log: true

- name: AAP2 Demo | Handle custom credentials
  when: aap2_custom_credentials is defined and aap2_custom_credentials | length > 0
  block:
    - name: AAP2 Demo | Create custom credentials
      ansible.controller.credential_type:
        name: "{{ item.credential_type }}"
        kind: cloud
        inputs: "{{ item.credential_type_inputs }}"
        injectors: "{{ item.credential_type_injectors }}"
        controller_host: "{{ aap2_controller_host }}"
        controller_username: "{{ aap2_controller_username }}"
        controller_password: "{{ aap2_controller_password }}"
        validate_certs: "{{ aap2_controller_validate_ssl | default(false, true) }}"
      loop: "{{ aap2_custom_credentials | to_json }}"

    - name: AAP2 Demo | Create credential from newly available type
      ansible.controller.credential:
        controller_host: "{{ aap2_controller_host }}"
        controller_username: "{{ aap2_controller_username }}"
        controller_password: "{{ aap2_controller_password }}"
        organization: "{{ aap2_organization | default('Default', true) }}"
        validate_certs: "{{ aap2_controller_validate_ssl | default(false, true) }}"
        name: "{{ item.name }}"
        state: present
        credential_type: "{{ item.credential_type }}"
        inputs: "{{ item.credential_inputs }}"
      loop: "{{ aap2_custom_credentials }}"
